const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const User = new Schema(
  {
    name: {
      type: String,
      required: true,
    },
    lastname: {
      type: String,
      required: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
    },
    uid: {
      type: String,
      required: true,
      unique: true,
    },
    userType: {
      type: String,
      required: true,
    },
    typeID: {
      type: String,
      required: false,
    },
    identificationNumber: {
      type: String,
      required: false,
    },
    dateOfBirth: {
      type: String,
      required: false,
    },
    cellphone: {
      type: String,
      required: false,
    },
    city: {
      type: String,
      required: false,
    },
    address: {
      type: String,
      required: false,
    },

    dateOfExpedition: { type: String, required: false },
    nameContactEmergency: { type: String, required: false },
    kinship: { type: String, required: false },
    cellphoneContactEmergency: { type: String, required: false },
    addressContactEmergency: { type: String, required: false },
    nickname: { type: String, required: false },
    cellphoneJob: { type: String, required: false },
    emailJob: { type: String, required: false },
    height: { type: String, required: false },
    skinTone: { type: String, required: false },
    hairLength: { type: String, required: false },
    hairColor: { type: String, required: false },
    breastType: { type: String, required: false },
    breastSize: { type: String, required: false },
    physicalBuild: { type: String, required: false },
    buttType: { type: String, required: false },
    buttSize: { type: String, required: false },
    modalityJob: { type: String, required: false },
    zoneJob: { type: String, required: false },
    extraPrice: { type: String, required: false },
    otherZoneJob: { type: String, required: false },
    halfHourPrice: { type: String, required: false },
    oneHourPrice: { type: String, required: false },
    twoHourPrice: { type: String, required: false },
    allDayPrice: { type: String, required: false },
    valueVaginalCondon: { type: String, required: false },
    valueVaginalSinCondon: { type: String, required: false },
    valueAnalCondon: { type: String, required: false },
    valueAnalSinCondon: { type: String, required: false },
    valueOralCondon: { type: String, required: false },
    valueOralSinCondon: { type: String, required: false },
    valueKisses: { type: String, required: false },
    valueTouchBreast: { type: String, required: false },
    valueTouchButtocks: { type: String, required: false },
    valueMasturbation: { type: String, required: false },
    valueTouchVagina: { type: String, required: false },
    valueInsertFingersVagina: { type: String, required: false },
    valueInsertToysOrObjectsVagina: { type: String, required: false },
    valueReceivingSexoOral: { type: String, required: false },
    lingerie: { type: String, required: false },
    valueLingerie: { type: String, required: false },
    others: { type: String, required: false },
    valueOthers: { type: String, required: false },
    valueBasicPhotoPack: { type: String, required: false },
    valuePremiumPhotoPack: { type: String, required: false },
    valueVideoPack: { type: String, required: false },
    valuePhotoAndVideoPack: { type: String, required: false },
    descriptionAdvertiser: { type: String, required: false },
    paymentType: { type: String, required: false },
    numberAccount: { type: String, required: false },
    experienceType: { type: String, required: false },
    profileType: { type: String, required: false },
    profileStatus: { type: String, required: false },
    images: { type: Object, required: false },

    // Campos booleanos
    vaginalCondon: { type: Boolean, required: false },
    vaginalSinCondon: { type: Boolean, required: false },
    analCondon: { type: Boolean, required: false },
    analSinCondon: { type: Boolean, required: false },
    oralCondon: { type: Boolean, required: false },
    oralSinCondon: { type: Boolean, required: false },
    kisses: { type: Boolean, required: false },
    touchBreast: { type: Boolean, required: false },
    touchButtocks: { type: Boolean, required: false },
    masturbation: { type: Boolean, required: false },
    touchVagina: { type: Boolean, required: false },
    insertFingersVagina: { type: Boolean, required: false },
    insertToysOrObjectsVagina: { type: Boolean, required: false },
    receivingSexoOral: { type: Boolean, required: false },
    includeVaginalCondon: { type: Boolean, required: false },
    includeVaginalSinCondon: { type: Boolean, required: false },
    includeAnalCondon: { type: Boolean, required: false },
    includeAnalSinCondon: { type: Boolean, required: false },
    includeOralCondon: { type: Boolean, required: false },
    includeOralSinCondon: { type: Boolean, required: false },
    includeTouchVagina: { type: Boolean, required: false },
    includeTouchBreast: { type: Boolean, required: false },
    includeTouchButtocks: { type: Boolean, required: false },
    includeKisses: { type: Boolean, required: false },
    includeMasturbation: { type: Boolean, required: false },
    includeInsertFingersVagina: { type: Boolean, required: false },
    includeInsertToysOrObjectsVagina: { type: Boolean, required: false },
    includeReceivingSexoOral: { type: Boolean, required: false },
    basicPhotoPack: { type: Boolean, required: false },
    includeBasicPhotoPack: { type: Boolean, required: false },
    premiumPhotoPack: { type: Boolean, required: false },
    includePremiumPhotoPack: { type: Boolean, required: false },
    videoPack: { type: Boolean, required: false },
    includeVideoPack: { type: Boolean, required: false },
    photoAndVideoPack: { type: Boolean, required: false },
    includePhotoAndVideoPack: { type: Boolean, required: false },
  },
  { timestamps: true }
);

module.exports = mongoose.model("users", User);
